[build-system]
# Minimum requirements for the build system to execute.
requires = ["wheel", "setuptools>=30.3.0", "attrs>=17.1", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | .eggs
  | build
)/
'''

[tool.check-manifest]
ignore = [
    'examples/**',
    'tests/**',
    'binder/**',
    '.*',
    'pyproject.toml',
    'pytest.ini',
    'CODE_OF_CONDUCT.md',
]

[tool.nbqa.config]
black = "pyproject.toml"

[tool.nbqa.mutate]
pyupgrade = 1
isort = 1
black = 1

[tool.nbqa.addopts]
pyupgrade = ["--py36-plus"]

[tool.isort]
profile = "black"
multi_line_output = 3
force_single_line = true
ignore_comments = true
float_to_top = true
